// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by GenerateControllerImportsPlugin

const controller0 = () => import('../features/products/controllers/ProductController');
const controller1 = () => import('../features/home/controllers/HomeController');
const controller2 = () => import('../features/contact/controllers/ContactController');

export const controllerModules = {
  '../features/products/controllers/ProductController.ts': controller0,
  '../features/home/controllers/HomeController.ts': controller1,
  '../features/contact/controllers/ContactController.ts': controller2
};

export const getControllerCount = () => 3;
