// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by GenerateControllerImportsPlugin

const controller0 = () => import('../features/user/controllers/UserController');
const controller1 = () => import('../controllers/ProductController');
const controller2 = () => import('../controllers/HomeController');
const controller3 = () => import('../controllers/ErrorController');
const controller4 = () => import('../controllers/ConfigController');
const controller5 = () => import('../controllers/AboutController');
const controller6 = () => import('../admin/controller/AdminController');

export const controllerModules = {
  '../features/user/controllers/UserController.ts': controller0,
  '../controllers/ProductController.ts': controller1,
  '../controllers/HomeController.ts': controller2,
  '../controllers/ErrorController.ts': controller3,
  '../controllers/ConfigController.ts': controller4,
  '../controllers/AboutController.ts': controller5,
  '../admin/controller/AdminController.ts': controller6
};

export const getControllerCount = () => 7;
